apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: opensearch
  labels:
    service: opensearch
spec:
  serviceName: opensearch
  # NOTE: This is number of nodes that we want to run
  # you may update this
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      # NOTE:
      # This is to fix the permission on the volume
      # By default elasticsearch container is not run as
      # non root user.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /opensearch-data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /opensearch-data
      # NOTE:
      # To increase the default vm.max_map_count to 262144
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      # To increase the ulimit
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: increase-the-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:latest
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        # NOTE: you can increase this resources
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        env:
          # NOTE: the cluster name; update this
          - name: cluster.name
            value: opensearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # NOTE: This will tell the opensearch node where to connect to other nodes to form a cluster
          - name: "discovery.seed_hosts"
            value: "opensearch-0.opensearch.opensearch.svc.cluster.local"
          - name: "cluster.initial_cluster_manager_nodes"
            value: "opensearch-0"
          # NOTE: You can increase the heap size
          - name: ES_JAVA_OPTS
            value: -Xms256m -Xmx256m
        volumeMounts:
        - name: data
          mountPath: /opensearch-data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      # storageClassName: ssd
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 5Gi
